# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Publish 1.1 docs

on:
  workflow_dispatch:

jobs:
  publish-docs:
    name: Publish documentation to nightlies.apache.org
    runs-on: ubuntu-latest
    if: github.repository == 'apache/pekko-http'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6

      - name: Build Documentation
        run: |-
          sbt -Dpekko.genjavadoc.enabled=true "set ThisBuild / version := \"1.1.0\"; docs/paradox; unidoc"
        env:
          JAVA_OPTS: "-verbose:gc -Xmx4g"

      # Create directory structure upfront since rsync does not create intermediate directories otherwise
      - name: Create directory structure
        run: |-
          mkdir -p target/nightly-docs/docs/pekko-http/1.1.0/
          mkdir -p target/nightly-docs/docs/pekko-http/1.1/
          cp -r docs/target/paradox/site/main/ target/nightly-docs/docs/pekko-http/1.1.0/docs
          cp -r docs/target/paradox/site/main/ target/nightly-docs/docs/pekko-http/1.1/docs
          rm -r docs/target/paradox/site/main/
          cp -r target/scala-2.13/unidoc target/nightly-docs/docs/pekko-http/1.1.0/api
          cp -r target/scala-2.13/unidoc target/nightly-docs/docs/pekko-http/1.1/api
          rm -r target/scala-2.13/unidoc
          cp -r target/javaunidoc target/nightly-docs/docs/pekko-http/1.1.0/japi
          cp -r target/javaunidoc target/nightly-docs/docs/pekko-http/1.1/japi
          rm -r target/javaunidoc

      - name: Upload 1.1.x nightly docs
        uses: ./.github/actions/sync-nightlies
        with:
          upload: true
          switches: --archive --compress --update --delete --progress --relative
          local_path: target/nightly-docs/./docs/pekko-http/1.1.0 # The intermediate dot is to show `--relative` which paths to operate on
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/pekko/
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}

      - name: Upload 1.1 nightly docs
        uses: ./.github/actions/sync-nightlies
        with:
          upload: true
          switches: --archive --compress --update --delete --progress --relative
          local_path: target/nightly-docs/./docs/pekko-http/1.1 # The intermediate dot is to show `--relative` which paths to operate on
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/pekko/
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}          
